### ISSUE TITLE
AppImage does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [ragnar-lodbrok/meow-sql#23]
`libstdc++.so.6: version 'GLIBCXX_3.4.20' not found`, please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

Reference:
https://github.com/AppImage/appimage.github.io/pull/442

**Comment by ragnar-lodbrok** [comment]
Thanks for reporting the bug and for linuxdeployqt tool.
I think it's tricky to use the patched AppRun, so I decided to make a build on Ubuntu 14.04.
You can find it on the releases page, but by some reason it looks slightly different (margin is smaller), so I think I'll provide two versions for now.

**Comment by probonopd** [comment]
> make a build on Ubuntu 14.04

Thank you, that's of course the best option. It should run on later versions as well.
