### ISSUE TITLE
Crash when inserting data in this table (columns missing in meow)

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#51]
I have this table:
```
CREATE TABLE `characters` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `name` char(50) NOT NULL,
  `world_id` int(10) unsigned NOT NULL,
  `x` int(10) unsigned NOT NULL,
  `y` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_character` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4
```

When I try to insert a row into this table with meow-sql, it crashes.
After some investigation, I notice that the tab 'Basic', which shows the columns in the table, doesn't show the x and y columns (only the first four columns are shown). The tab 'Data' however does show the x and y column. But when I try to insert data in that tab, meow-sql crashes.

**Comment by ragnar-lodbrok** [comment]
@scippie75 
Thanks for reporting, the problem was in  parsing column names of length == 1 (`x`, `y`). You can keep `character`, it should work. Renaming `x` and `y` to something longer should help if this is an option for you. Let me know if you need new build with the fix.

**Comment by scippie75** [comment]
Oh, that's fine, I'll use pos_x and pos_y. I'm very grateful for your work. Finally a decent working port for HeidiSQL on Linux!
Keep up the good work!
