### ISSUE TITLE
Feature request: better HiDPI support on Linux

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#52]
While I think it adjusts to high dpi, it is still very small on my 4K screen, while it is very readable on my Full HD screen.
It is usable, but I would like it if it could scale a bit more.
Other hidpi aware applications seem to do it fine, so I guess it should be possible.

I attached a screenshot to show you how much space on the screen is unused. Sorry for the blurriness, it's highly top secret :-D.

The connection screen is also very small.

I would greatly appreciate it if something could be done. I can be your tester if you need it!
![2020-09-10-231528_3840x2115_scrot](https://user-images.githubusercontent.com/30812282/92808158-c8b59a00-f3bb-11ea-8521-f93b985ed349.png)

**Comment by scippie75** [comment]
I'd like to add that some controls also don't show up correctly with HiDPI. See screenshot.
![2020-09-29-142730_800x400_scrot](https://user-images.githubusercontent.com/30812282/94558272-080b3400-0260-11eb-9113-30f1c0ec66aa.png)

**Comment by ragnar-lodbrok** [comment]
I [don't have](https://ko-fi.com/ragnarlodbrok) a 4K display, but KDE scales the app just fine on my 141.2 PPI notebook when I set appropriate scaling (115%).

Try to set QT_AUTO_SCREEN_SCALE_FACTOR environment variable to true like that:
`QT_AUTO_SCREEN_SCALE_FACTOR=1 ./Linux_MeowSQL_0.4.4-x86_64.AppImage`

**Comment by scippie75** [comment]
That is indeed better! Thanks! I'll put this in my .xinitrc
