### ISSUE TITLE
Dropdown popup on multiple screens (of different size) (on Linux)

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#53]
I use meow on my second monitor. It is a 1:1 screen (yes, square, it's fantastic for developers) but I don't think it is the problem.
When I create (or alter) a table and want to select 'AUTO_INCREMENT' on the Default column, the popup opens up on my other screen in the upper right corner.
Because my left, normal full HD screen is positioned somewhere halfway the 1:1 screen, the popup opens up 'above' the screen and the only item I can see is the last one (which luckily is AUTO_INCREMENT).

I don't know if it's related, but I use the i3 windowing manager.

Obviously, the expected result is that it opens up at the cursor.

I hope you can fix it :-)
Sorry for all the nagging, but I'm for one a good tester ;-)

**Comment by ragnar-lodbrok** [comment]
@scippie75 Seems fixed in the new version, please check: https://github.com/ragnar-lodbrok/meow-sql/releases/tag/v0.4.4-alpha

**Comment by scippie75** [comment]
Yes, I can confirm!
