### ISSUE TITLE
Unknown table 'COLUMN_STATISTICS' on Export database

### ISSUE THREAD

**Issue by jonathangreco** [ragnar-lodbrok/meow-sql#56]
![image](https://user-images.githubusercontent.com/1587180/93492671-5b4dc000-f90b-11ea-8bbb-e2c243882ef6.png)

**Comment by ragnar-lodbrok** [comment]
@jonathangreco Export always provides table's data, try to open the result file to see. Do you want new option to disable dumping data?

**Comment by jonathangreco** [comment]
You've right sorry : the thing is i encountered an error in the log that I missed in the first place, I just didn't see my data in the exported file without noticing data is actually here : 

The error i got was : 
`mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'my_project' AND TABLE_NAME = 'doctrine_migration_versions';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
`

**Comment by ragnar-lodbrok** [comment]
Looks like your case: https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109

I need to add `--column-statistics=0` into dumping. You may disable it in your config, see accepted SO answer above.

**Comment by jonathangreco** [comment]
Yes i think you need to add this as it may introduce this error randomly for no gain at all

**Comment by ragnar-lodbrok** [comment]
@jonathangreco 

Please post out put of `mysqldump --version`

**Comment by jonathangreco** [comment]
`mysqldump  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))`

**Comment by ragnar-lodbrok** [comment]
@jonathangreco I've added a new checkbox option "Disable column statistics" that should allow to export the data. 
Would be nice if you could test that 1) If you mark it, dump works 2) this checkbox is on for you by default (should be on for mysqldump v8).

AppImage build if you need: https://www.dropbox.com/t/nZ2IKo8vc047akZl

![image](https://user-images.githubusercontent.com/11667345/94945753-58ef8680-0505-11eb-9b94-03dba9230bd1.png)
