### ISSUE TITLE
Refresh Data tab when switch tabs and/or add refresh-button

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#57]
Especially when your change the Table layout in the Table tab, the Data tab is outdated. HeidiSQL does this if I remember correctly _and it's useful_.
I leave it up to you whether it should always refresh on tab-switch, or only when changing the table layout (or don't if you add a refresh button).
And a refresh button (which can be activated with the F5 hotkey) would also be nice. It doesn't seem to work now, but it also doesn't work in the left column (where it is mentioned in the right-click menu). I'm on Linux, so maybe it doesn't work there yet.

**Comment by jonathangreco** [comment]
Hey !
Is the issue #54 related ?

If so the author has replied that this alpha https://github.com/ragnar-lodbrok/meow-sql/releases/tag/v0.4.4-alpha should fix the issue.

**Comment by scippie75** [comment]
I'm not sure, I have built the latest git version (Arch Linux AUR). Is that fix in there?
Anyway, F5 doesn't seem to respond on my pc, not on the left nor on the right view.

**Comment by ragnar-lodbrok** [comment]
Yup, F5 doesn't work yet, only context menu item.

**Comment by scippie75** [comment]
Would it be possible to add a 'refresh' button to the top bar next to that add/remove buttons? It would certainly be better than the slower system with right-clicking in an empty area.

**Comment by ragnar-lodbrok** [comment]
- F5 hotkey should refresh data and left tree depending on where is the focus.
- Changing table layout invalidates data, so you don't need to refresh it manually
- Refresh button is added to Data tab
