### ISSUE TITLE
Deleting an item in the Data tab doesn't work

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#58]
When a row is selected (it's a table without primary key), the query to delete a row is incorrect, it doesn't have a WHERE and it contains a LIMIT 1. I don't really think the LIMIT should be there and it should definitely contain the WHERE with probably all columns in it.

**Comment by ragnar-lodbrok** [comment]
So I changed the logic: if table has no primary key, then unique key is used (to be more precise unique key columns must be with allow null == false). If no suitable unique key is found - all table columns are used. This should also fix editing and inserting into such tables.

**Comment by scippie75** [comment]
Sounds great! :+1:
