### ISSUE TITLE
Strange issue when inserting in Data tab

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#59]
I just added a row with the + button. I filled in the fields and usually I will then click some other row so that the insert is triggered.
This time, however, after filling in the fields, I wanted to add another row, so I immediately clicked + again. The first row became complete NULL-ed (and was not inserted). If I then switched table and went back the Data tab showed lots of empty rows (really empty, not even NULL or something).

**Comment by ragnar-lodbrok** [comment]
@scippie75 Let me guess, your table has no primary key? 
Can you post `SHOW CREATE TABLE name`

**Comment by scippie75** [comment]
No, it has a primary key.

```
CREATE TABLE `jobs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `task` enum('foo','bar') NOT NULL,
  `host` char(255) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `succeeded` enum('Y','N') DEFAULT NULL,
  `error` text,
  PRIMARY KEY (`id`),
  KEY `Index 2` (`succeeded`)
) ENGINE=InnoDB AUTO_INCREMENT=594 DEFAULT CHARSET=latin1
```

**Comment by ragnar-lodbrok** [comment]
Thanks for reporting.
To be fair, in HeidiSQL it doesn't insert new rows as well. You need to modify row to insert it. 

However I agree that there is a bug: the app should not allow to insert new unsaved rows silently.

![Peek_heidi_insert](https://user-images.githubusercontent.com/11667345/94994403-96194e80-05c1-11eb-8cc5-c3291db45a1e.gif)

**Comment by scippie75** [comment]
Ok, you're right with your example but it doesn't really show what I mean:

In HeidiSQL, I used to go to the lowest row and just push the 'down arrow' on the keyboard. It creates a new empty row like the one in your example / when pushing the + button. If I then fill in these fields and then press the 'down arrow' again, it will insert the filled in row and create a new empty one.

**Comment by scippie75** [comment]
I think I now understand the problem better. In HeidiSQL, when you edit a row and then 'leave' that row by clicking somewhere else outside that row, albeit clicking another button, pressing the keyboard arrow up/down, ..., it will automatically post that row, which in Meow-sql needs to be done explicitly with the post button on top.

**Comment by ragnar-lodbrok** [comment]
I made some fixes here, was able to repeat empty rows problem. However inserting completely unmodified row is still ignored (you need to change any cell to insert the row by changing the row). I also had to disable inserting new row while you edit another new row.

**Comment by scippie75** [comment]
Thanks. I'll close this for now. If I encounter it again, I'll reopen it.
