### ISSUE TITLE
Request: rename database

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#60]
One reason I still start up HeidiSql through Wine (ugh) is because I need to rename a database. Usually this is to add the '_old'-suffix or something like this, just to make sure it's not gone when it was a wrong decision to remove it.

I'd love to see that functionality in MeowSql. HeidiSQL does several 'hacky' queries directly on the schema database, so I guess this is something that should be tested thoroughly.

I haven't found a simple SQL query to rename the database in MariaDB yet.

**Comment by ragnar-lodbrok** [comment]
@scippie75 Please check master for this feature. I didn't test it well, so backup everything before trying.
