### ISSUE TITLE
Bug: crash, can't say exactly where...

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#65]
I can't tell where it is, but if I do these steps, I get it every time (Linux):
- Start meow-sql, open a connection to a database
- In the left bar, select a table under a specific database
- Go to the Data tab and refresh there a couple of times (5x? once may also be enough) with F5
- Click another table in the left bar (try again with a different table if crash not immediately there)
-> crash

Extra info:
- I built meow-sql from source
- I connect to a named hostname which is 127.0.0.1 in /etc/hosts, port 3306 (I work with a self-created tunnel through a jump-host, so your ssh-tunnel is insufficient)

**Comment by ragnar-lodbrok** [comment]
Should be fixed in `master`.
