### ISSUE TITLE
Feature request : Date field with a date time picker to ease select a date

### ISSUE THREAD

**Issue by jonathangreco** [ragnar-lodbrok/meow-sql#66]
From what i remember HeidiSQL already provided it, when we click on a date (timestamp) a picker appeared.

It would be nice to have this one, because each time we want to fill a date manually in the database we need to write it down correctly (Y-m-d format...) And it's a total waste of time :p 

Again thanks for your work I just tested filters it's working well :+1:

**Comment by ragnar-lodbrok** [comment]
@jonathangreco Please check the latest version: https://github.com/ragnar-lodbrok/meow-sql/releases/tag/v0.4.8-alpha

![image](https://user-images.githubusercontent.com/11667345/105036341-ef34c180-5a8e-11eb-8d32-2a3972f09e67.png)

**Comment by jonathangreco** [comment]
@ragnar-lodbrok tested, it works perfectly, thank you !
