### ISSUE TITLE
Feature request : Possibility to filtering Databases in the left panel

### ISSUE THREAD

**Issue by jonathangreco** [ragnar-lodbrok/meow-sql#68]
As shown below It would be nice to have the same filter panel for the result in the Data tab, to the Database tab.

Some system, like ours, has a lot of Databases (more than 100 sometimes) it's a complete mess to scroll on those when we only need one of them.

![Capture d’écran de 2020-12-20 01-40-43](https://user-images.githubusercontent.com/1587180/102702557-701c5580-4264-11eb-94b4-d723d79ca68f.png)

This filter could be  activated by default and Ctrl + F will focus on the field to automatically search DB.
While Ctrl+Alt+F should automatically focus on the right filter field (in the browser for example Ctrl+F put the focus on the field and allow the search directly we should have the same behaviour)

**Comment by amosbird** [comment]
Is it available for table list now? I cannot see any filter panel after pressing the button

![Uploading image.png…]()

**Comment by ragnar-lodbrok** [comment]
@amosbird Nope, it is not available yet. The filter panel is a right-side one and appears for Data tab only at the moment.
In the mean time you can type first letters of your table (when table list is expanded and focused) to jump to required entity.

**Comment by ragnar-lodbrok** [comment]
See v0.4.11
