### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by stuzer05** [ragnar-lodbrok/meow-sql#69]
```make: *** No rule to make target 'db/user_manager.cpp', needed by 'build-meow-sql-Desktop-Debug/db/user_manager.o'.  Stop.```
File `user_manager.cpp` got removed in recent commit and it's .h file still exists. Also `user_manager.cpp` is listed in .pro file

When I remove `user_manager.cpp` from .pro file I get linker errors
```
/usr/bin/ld: ./ui/main_window/main_window.o: in function `meow::ui::main_window::Window::onUserManagerAction()':
/build-meow-sql-Desktop-Debug/../meow-sql/meow-sql/ui/main_window/main_window.cpp:148: undefined reference to `meow::ui::user_manager::Window::Window(meow::ui::main_window::Window*, meow::db::SessionEntity*)'
/usr/bin/ld: /build-meow-sql-Desktop-Debug/../meow-sql/meow-sql/ui/main_window/main_window.cpp:150: undefined reference to `meow::ui::user_manager::Window::~Window()'
/usr/bin/ld: /build-meow-sql-Desktop-Debug/../meow-sql/meow-sql/ui/main_window/main_window.cpp:150: undefined reference to `meow::ui::user_manager::Window::~Window()'
/usr/bin/ld: ./db/mysql/mysql_connection.o: in function `meow::db::MySQLConnection::createUserManager()':
/build-meow-sql-Desktop-Debug/../meow-sql/meow-sql/db/mysql/mysql_connection.cpp:531: undefined reference to `meow::db::MySQLUserManager::MySQLUserManager(meow::db::Connection*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ragnar-lodbrok** [comment]
Normally you should use master branch for your builds unless you develop a feature. 
I use CMake as a primary platform, .pro/QMake builds are "just in case", so usually I make it compilable before merging to master.
Anyway, pull latest commit for fixes.

**Comment by stuzer05** [comment]
Thanks for fixing! Yes, I would like to contribute and it'll take some time to get familiar with the codebase. Do you mind filling the milestone issues?

**Comment by ragnar-lodbrok** [comment]
Well, I don't have long-lasting milestones planning (do what I need for myself or what requested), but you can refer to rough [ROADMAP](https://github.com/ragnar-lodbrok/meow-sql/blob/master/ROADMAP.md) where the features are somehow sorted by priority.

You also can pick up any unassigned "help wanted" issue  https://github.com/ragnar-lodbrok/meow-sql/labels/help%20wanted

Another option is searching for TODOs and backporting fixes/changes from [original project](https://github.com/HeidiSQL/HeidiSQL).

**Comment by ragnar-lodbrok** [comment]
@stuzer05 thanks for reporting bugs, coffee and PRs, but I need to warn you that I may accept PRs with some delay (having busy days).
