### ISSUE TITLE
Insert new records without providing auto-incrementing column

### ISSUE THREAD

**Issue by amosbird** [ragnar-lodbrok/meow-sql#83]
Currently I cannot find a way to insert new records with auto-increment keys. Is it possible now or still a missing feature?

**Comment by ragnar-lodbrok** [comment]
![auto_inc](https://user-images.githubusercontent.com/11667345/111026277-0901dd80-841c-11eb-8819-1841934a0115.gif)

**Comment by amosbird** [comment]
Thanks!
