### ISSUE TITLE
How can I remove the `limit 1000` limitation?

### ISSUE THREAD

**Issue by amosbird** [ragnar-lodbrok/meow-sql#84]
After playing for a while, I still cannot find any way to configure meow-sql...

**Comment by ragnar-lodbrok** [comment]
@amosbird There is no such setting yet, you can only recompile the code and set DATA_ROWS_PER_STEP const in db/common.h to your value.

Alternatively you could click on "Show all" button.
![image](https://user-images.githubusercontent.com/11667345/118297095-e9fcf600-b507-11eb-8c4b-c9f7f64e7433.png)

**Comment by amosbird** [comment]
Thanks
