### ISSUE TITLE
fatal error: postgresql/libpq-fe.h: No such file or directory

### ISSUE THREAD

**Issue by beliys** [ragnar-lodbrok/meow-sql#85]
When compiling on Arch and distributions based on it, we get an error:
```
fatal error: postgresql/libpq-fe.h: No such file or directory
```
At the same time, the postgresql-libs package is installed, but in order to compile it is necessary to apply a patch in the form of replacing `#include <postgresql/libpq-fe.h>` with `#include <libpq-fe.h>`
To what extent is it possible to take this point into account in the original code to be able to compile on arch-based distributions?

**Comment by ragnar-lodbrok** [comment]
@beliys See 90f1fd1
