### ISSUE TITLE
User manager issue (MariaDB 10.4)

### ISSUE THREAD

**Issue by TomMettam** [ragnar-lodbrok/meow-sql#94]
When attempting to enter the User Manager on a MariaDB 10.4 server..

https://gyazo.com/6cc1464f4e30feee3952f596cd49acb9

**Comment by TomMettam** [comment]
![6cc1464f4e30feee3952f596cd49acb9](https://user-images.githubusercontent.com/2168418/174147298-a30b01c0-a827-4dfe-961c-10b8fed65275.png)

**Comment by ragnar-lodbrok** [comment]
@TomMettam Please check the latest release.
Never tested the app with MariaDB, would be nice if you test/report other bugs.

**Comment by TomMettam** [comment]
User manager seems to work now. Thanks! I'll report any issues as i encounter them.
